export PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb:64,garbage_collection_threshold:0.6"

CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage sft \
    --do_train \
    --model_name_or_path /home/wangyc/verl/Qwen/Qwen2.5-7B-Instruct \
    --dataset legal_multi_choice \
    --dataset_dir /home/wangyc/verl/data \
    --template qwen \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --lora_r 64 \
    --lora_alpha 128 \
    --output_dir /home/wangyc/verl/checkpoints/law-sft-qwen-2.5-7b-instruct \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 8 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --warmup_ratio 0.1 \
    --save_strategy steps \
    --save_steps 200 \
    --learning_rate 2e-4 \
    --num_train_epochs 2.0 \
    --max_grad_norm 0.5 \
    --bf16 \
    --gradient_checkpointing \
    --report_to wandb \
    --flash_attn fa2 \
    --use_llama_pro